version: 2.1
executors:
  default:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo


jobs:
  checkout_repository:
    executor: default
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dump
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-RawTextRepository-{{ .Environment.CIRCLE_SHA1 }}
            - v1-RawTextRepository-

      - save_cache:
          paths:
            - ~/repo
          key: v1-RawTextRepository-{{ .Environment.CIRCLE_SHA1 }}

  build_and_test:
    executor: default
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dump
    steps:
      - restore_cache:
          keys:
            - v1-RawTextRepository-{{ .Environment.CIRCLE_SHA1 }}
            - v1-RawTextRepository-
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
              - v1-dependencies-
      - run: echo $GCLOUD_SERVICE_KEY | base64 -d > /home/circleci/repo/credential.json
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn compile
      - run: mvn integration-test

      - store_test_results:
          path: target/surefire-reports



workflows:
  version: 2
  test:
    jobs:
      - checkout_repository
      - build_and_test:
          requires:
            - checkout_repository